[package]
name = "eww_update_vars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envmnt = "0.10.4"
serde = "1.0.164"
serde_json = "1.0.96"
